### ISSUE TITLE
cannot call 'Init', 'mt4-common.dll' is not loaded

### ISSUE THREAD

**Issue by liuyan814** [mikha-dev/mt4-websockets#12]
The new version of MT5 prompts this error when called:
cannot call 'Init', 'mt4-common.dll' is not loaded
The file is also under the path, it just says it can't be loaded.
What is the reason for this?

**Comment by segomaster** [comment]
Having the same issue

**Comment by segomaster** [comment]
> The new version of MT5 prompts this error when called: cannot call 'Init', 'mt4-common.dll' is not loaded The file is also under the path, it just says it can't be loaded. What is the reason for this?

Make sure to install Latest Microsoft Visual C++ Redistributable That worked for me.

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by liuyan814** [comment]
> > The new version of MT5 prompts this error when called: cannot call 'Init', 'mt4-common.dll' is not loaded The file is also under the path, it just says it can't be loaded. What is the reason for this?
> 
> Make sure to install Latest Microsoft Visual C++ Redistributable That worked for me.
> 
> https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

Thank you very much, after installing it, it no longer prompts an error.
