### ISSUE TITLE
mt4-common.dll's Init function makes EA crash 

### ISSUE THREAD

**Issue by vianeostech** [mikha-dev/mt4-websockets#6]
Hi Mikha,

Thanks the great job.
I have several MT4 instances, on one of them the code just works fine. On all of the others mt4-common.dll's Init function makes EA crash, the initial request comes from ws.Init() within EA.
I tried to copy again provided files, tried also using your EA sample but no EA works. 
Unfortunately there is nothing in the logs either.

Any help would be much appreciated.

Thanks.

**Comment by mikha-dev** [comment]
Hello,

I am using it on 300 mt4 per PC, no issue so far. Maybe you have problems on ws server side? What ws server do you use?

**Comment by vianeostech** [comment]
Hello Mikha, 

thanks for your answer.
I am using openswoole as WS server. But the EA seems to not even try to connect to the server. 
It is really strange that the library makes EA crash on all my MT4 instances except one.
I can not succeed to make it work on any other, even on a different Windows machine. 
What WS server are you using on your side ?

Thx for your feedback.

**Comment by mikha-dev** [comment]
I am using own server based on ixwebsocket lib.

**Comment by vianeostech** [comment]
Hi Mikhail,

are you running a specific version of MT4 ?
Which one is yours please ?

Regards

**Comment by mikha-dev** [comment]
common version of mt4. on all versions of mt4 last 4 years. also on latest one

**Comment by mikha-dev** [comment]
try to use it with my ws server

135.181.114.34:8080

**Comment by vianeostech** [comment]
Hi Mikhail,

thx. Let me try with your server and I will get back to you ASAP.
BTW I tried to use web sockets EA twice on the same MT4 but on different charts, this make MT4 crash, it seems that it is not possible to enable 2 different websockets on the same MT4 terminal.
Waiting for your kind feedback.

Regards

**Comment by vianeostech** [comment]
Hi Mikhail,

I tested your WS server several times with the EA but it crashes the same way at Init() function step.

Do you have any idea ?

**Comment by mikha-dev** [comment]
Hi, 

sorry don`t have ideas. Going to close Issue if you don`t mind.
