### ISSUE TITLE
Build on mql5

### ISSUE THREAD

**Issue by tonnyec** [mikha-dev/mt4-websockets#7]
Hello,
when compiling in mql5 64bits I have this warning:

deprecated behavior, hidden method calling will be disabled in a future MQL compiler version	lib_websockets.mqh	86	16

![image](https://user-images.githubusercontent.com/1947259/202836098-1011b7c6-fffa-4452-9527-da9052d2a98b.png)

But it builds without errors.
However when running it doesn't work.

![image](https://user-images.githubusercontent.com/1947259/202836150-8bdb249d-4251-4aa7-89a3-23fa3a913694.png)

This is a version of mt5
![image](https://user-images.githubusercontent.com/1947259/202836180-912c4097-0c3f-47f3-a5f2-1b2a18b0b8b2.png)

Thanks since now!

**Comment by mikha-dev** [comment]
Hello, dll complied with support of x86. never used on x64
